import { Room, GuestReservation, RatePlan } from './types';

export const INITIAL_CATEGORIES: string[] = [
  'Standard',
  'Luxo',
  'Suíte Master',
  'Chalé Vista',
  'Vila Privativa',
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'r-101',
    number: '101',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'ocupado',
    dailyRate: 220,
    capacity: 2,
    currentGuestId: 'g-01',
    currentGuestName: 'Carlos Eduardo Santos',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-06',
  },
  {
    id: 'r-102',
    number: '102',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-103',
    number: '103',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'limpeza',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-104',
    number: '104',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-201',
    number: '201',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'ocupado',
    dailyRate: 340,
    capacity: 3,
    currentGuestId: 'g-02',
    currentGuestName: 'Mariana Azevedo Costa',
    checkInDate: '2026-09-03',
    checkOutDate: '2026-09-07',
  },
  {
    id: 'r-202',
    number: '202',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'livre',
    dailyRate: 340,
    capacity: 3,
  },
  {
    id: 'r-203',
    number: '203',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'ocupado',
    dailyRate: 340,
    capacity: 3,
    currentGuestId: 'g-03',
    currentGuestName: 'Roberto Albuquerque',
    checkInDate: '2026-09-01',
    checkOutDate: '2026-09-05',
  },
  {
    id: 'r-301',
    number: '301',
    type: 'Suíte Master',
    area: 'Cobertura com Ofurô',
    status: 'ocupado',
    dailyRate: 520,
    capacity: 2,
    currentGuestId: 'g-04',
    currentGuestName: 'Beatriz Vasconcelos',
    checkInDate: '2026-09-04',
    checkOutDate: '2026-09-09',
  },
  {
    id: 'r-302',
    number: '302',
    type: 'Suíte Master',
    area: 'Cobertura com Ofurô',
    status: 'limpeza',
    dailyRate: 520,
    capacity: 2,
  },
  {
    id: 'r-ch01',
    number: 'CH-01',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'livre',
    dailyRate: 460,
    capacity: 4,
  },
  {
    id: 'r-ch02',
    number: 'CH-02',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'ocupado',
    dailyRate: 460,
    capacity: 4,
    currentGuestId: 'g-05',
    currentGuestName: 'Felipe & Camila Brandão',
    checkInDate: '2026-09-03',
    checkOutDate: '2026-09-08',
  },
  {
    id: 'r-ch03',
    number: 'CH-03',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'manutenção',
    dailyRate: 460,
    capacity: 4,
  },
  {
    id: 'r-vl01',
    number: 'VILA-01',
    type: 'Vila Privativa',
    area: 'Jardim das Palmeiras (Piscina)',
    status: 'ocupado',
    dailyRate: 980,
    capacity: 6,
    currentGuestId: 'g-06',
    currentGuestName: 'Família Mendonça',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-10',
  },
  {
    id: 'r-vl02',
    number: 'VILA-02',
    type: 'Vila Privativa',
    area: 'Jardim das Palmeiras (Piscina)',
    status: 'livre',
    dailyRate: 980,
    capacity: 6,
  },
];

export const INITIAL_GUESTS: GuestReservation[] = [
  {
    id: 'g-01',
    name: 'Carlos Eduardo Santos',
    document: '298.412.875-10',
    phone: '(11) 98711-2244',
    email: 'carlos.eduardo@email.com',
    city: 'São Paulo/SP',
    roomNumber: '101',
    checkIn: '2026-09-02',
    checkOut: '2026-09-06',
    numGuests: 2,
    dailyRate: 220,
    discount: 0,
    totalAmount: 880,
    paymentMethod: 'PIX (50% adiantado)',
    status: 'Hospedado',
    notes: 'Solicitou travesseiros antialérgicos adicionais.',
    createdAt: '2026-08-25',
  },
  {
    id: 'g-02',
    name: 'Mariana Azevedo Costa',
    document: '142.890.321-44',
    phone: '(21) 99342-8877',
    email: 'mariana.costa@email.com',
    city: 'Rio de Janeiro/RJ',
    roomNumber: '201',
    checkIn: '2026-09-03',
    checkOut: '2026-09-07',
    numGuests: 2,
    dailyRate: 340,
    discount: 0,
    totalAmount: 1360,
    paymentMethod: 'Cartão de Crédito 2x',
    status: 'Hospedado',
    notes: 'Aniversário de casamento. Deixar cartão boas-vindas.',
    createdAt: '2026-08-28',
  },
  {
    id: 'g-03',
    name: 'Roberto Albuquerque',
    document: '085.341.678-90',
    phone: '(31) 98455-1100',
    email: 'albuquerque.eng@email.com',
    city: 'Belo Horizonte/MG',
    roomNumber: '203',
    checkIn: '2026-09-01',
    checkOut: '2026-09-05',
    numGuests: 1,
    dailyRate: 340,
    discount: 40,
    totalAmount: 1320,
    paymentMethod: 'Transferência Bancária',
    status: 'Hospedado',
    notes: 'Check-out antecipado previsto às 09:00.',
    createdAt: '2026-08-20',
  },
  {
    id: 'g-04',
    name: 'Beatriz Vasconcelos',
    document: '331.782.905-22',
    phone: '(41) 99123-4567',
    email: 'beatriz.vasc@email.com',
    city: 'Curitiba/PR',
    roomNumber: '301',
    checkIn: '2026-09-04',
    checkOut: '2026-09-09',
    numGuests: 2,
    dailyRate: 520,
    discount: 0,
    totalAmount: 2600,
    paymentMethod: 'Cartão de Crédito à vista',
    status: 'Hospedado',
    notes: 'Chegada tardia confirmada após as 20h.',
    createdAt: '2026-09-01',
  },
  {
    id: 'g-05',
    name: 'Felipe & Camila Brandão',
    document: '419.602.118-73',
    phone: '(19) 98833-2211',
    email: 'felipe.brandao@email.com',
    city: 'Campinas/SP',
    roomNumber: 'CH-02',
    checkIn: '2026-09-03',
    checkOut: '2026-09-08',
    numGuests: 3,
    dailyRate: 460,
    discount: 0,
    totalAmount: 2300,
    paymentMethod: 'PIX Integral',
    status: 'Hospedado',
    notes: 'Cama extra para criança de 6 anos.',
    createdAt: '2026-08-15',
  },
  {
    id: 'g-06',
    name: 'Família Mendonça',
    document: '512.904.771-08',
    phone: '(11) 97722-9900',
    email: 'mendonca.adv@email.com',
    city: 'Santos/SP',
    roomNumber: 'VILA-01',
    checkIn: '2026-09-02',
    checkOut: '2026-09-10',
    numGuests: 5,
    dailyRate: 980,
    discount: 240,
    totalAmount: 7600,
    paymentMethod: 'Cartão Corporativo',
    status: 'Hospedado',
    notes: 'Vila com churrasqueira e piscina aquecida reservada.',
    createdAt: '2026-08-10',
  },
  {
    id: 'g-07',
    name: 'Luciana Martins Pereira',
    document: '189.234.901-55',
    phone: '(61) 99876-5432',
    email: 'luciana.mp@email.com',
    city: 'Brasília/DF',
    roomNumber: '102',
    checkIn: '2026-09-08',
    checkOut: '2026-09-12',
    numGuests: 2,
    dailyRate: 220,
    discount: 0,
    totalAmount: 880,
    paymentMethod: 'Aguardando check-in',
    status: 'Confirmada',
    notes: 'Reserva pelo portal direto. Sinal pago 30%.',
    createdAt: '2026-09-02',
  },
  {
    id: 'g-08',
    name: 'Danilo Ramos Siqueira',
    document: '274.551.982-12',
    phone: '(85) 98111-4477',
    email: 'danilo.ramos@email.com',
    city: 'Fortaleza/CE',
    roomNumber: 'CH-01',
    checkIn: '2026-09-11',
    checkOut: '2026-09-15',
    numGuests: 2,
    dailyRate: 460,
    discount: 50,
    totalAmount: 1790,
    paymentMethod: 'PIX',
    status: 'Confirmada',
    notes: 'Lua de mel. Preparar espumante cortesia na chegada.',
    createdAt: '2026-09-03',
  }
];

export const INITIAL_RATE_PLANS: RatePlan[] = [
  {
    id: 'rate-1',
    roomType: 'Standard',
    lowSeasonRate: 190,
    midSeasonRate: 240,
    highSeasonRate: 310,
    holidayRate: 420,
    extraPersonRate: 70,
    minNights: 1,
  },
  {
    id: 'rate-2',
    roomType: 'Luxo',
    lowSeasonRate: 290,
    midSeasonRate: 360,
    highSeasonRate: 450,
    holidayRate: 600,
    extraPersonRate: 90,
    minNights: 2,
  },
  {
    id: 'rate-3',
    roomType: 'Suíte Master',
    lowSeasonRate: 450,
    midSeasonRate: 550,
    highSeasonRate: 690,
    holidayRate: 890,
    extraPersonRate: 120,
    minNights: 2,
  },
  {
    id: 'rate-4',
    roomType: 'Chalé Vista',
    lowSeasonRate: 390,
    midSeasonRate: 480,
    highSeasonRate: 620,
    holidayRate: 780,
    extraPersonRate: 100,
    minNights: 2,
  },
  {
    id: 'rate-5',
    roomType: 'Vila Privativa',
    lowSeasonRate: 850,
    midSeasonRate: 1050,
    highSeasonRate: 1350,
    holidayRate: 1800,
    extraPersonRate: 150,
    minNights: 3,
  },
];
