import { Room, GuestReservation, RatePlan, Employee, InventoryItem, StockExitRecord } from './types';

export const INITIAL_CATEGORIES: string[] = [
  'Standard',
  'Luxo',
  'Suíte Master',
  'Chalé Vista',
  'Vila Privativa',
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'r-101',
    number: '101',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'ocupado',
    dailyRate: 220,
    capacity: 2,
    currentGuestId: 'g-01',
    currentGuestName: 'Carlos Eduardo Santos',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-06',
  },
  {
    id: 'r-102',
    number: '102',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-103',
    number: '103',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'limpeza',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-104',
    number: '104',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-201',
    number: '201',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'ocupado',
    dailyRate: 340,
    capacity: 3,
    currentGuestId: 'g-02',
    currentGuestName: 'Mariana Azevedo Costa',
    checkInDate: '2026-09-03',
    checkOutDate: '2026-09-07',
  },
  {
    id: 'r-202',
    number: '202',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'livre',
    dailyRate: 340,
    capacity: 3,
  },
  {
    id: 'r-203',
    number: '203',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'ocupado',
    dailyRate: 340,
    capacity: 3,
    currentGuestId: 'g-03',
    currentGuestName: 'Roberto Albuquerque',
    checkInDate: '2026-09-01',
    checkOutDate: '2026-09-05',
  },
  {
    id: 'r-301',
    number: '301',
    type: 'Suíte Master',
    area: 'Cobertura com Ofurô',
    status: 'ocupado',
    dailyRate: 520,
    capacity: 2,
    currentGuestId: 'g-04',
    currentGuestName: 'Beatriz Vasconcelos',
    checkInDate: '2026-09-04',
    checkOutDate: '2026-09-09',
  },
  {
    id: 'r-302',
    number: '302',
    type: 'Suíte Master',
    area: 'Cobertura com Ofurô',
    status: 'limpeza',
    dailyRate: 520,
    capacity: 2,
  },
  {
    id: 'r-ch01',
    number: 'CH-01',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'livre',
    dailyRate: 460,
    capacity: 4,
  },
  {
    id: 'r-ch02',
    number: 'CH-02',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'ocupado',
    dailyRate: 460,
    capacity: 4,
    currentGuestId: 'g-05',
    currentGuestName: 'Felipe & Camila Brandão',
    checkInDate: '2026-09-03',
    checkOutDate: '2026-09-08',
  },
  {
    id: 'r-ch03',
    number: 'CH-03',
    type: 'Chalé Vista',
    area: 'Bosque Superior',
    status: 'manutenção',
    dailyRate: 460,
    capacity: 4,
  },
  {
    id: 'r-vl01',
    number: 'VILA-01',
    type: 'Vila Privativa',
    area: 'Jardim das Palmeiras (Piscina)',
    status: 'ocupado',
    dailyRate: 980,
    capacity: 6,
    currentGuestId: 'g-06',
    currentGuestName: 'Família Mendonça',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-10',
  },
  {
    id: 'r-vl02',
    number: 'VILA-02',
    type: 'Vila Privativa',
    area: 'Jardim das Palmeiras (Piscina)',
    status: 'livre',
    dailyRate: 980,
    capacity: 6,
  },
];

export const INITIAL_GUESTS: GuestReservation[] = [
  {
    id: 'g-01',
    name: 'Carlos Eduardo Santos',
    document: '298.412.875-10',
    phone: '(11) 98711-2244',
    email: 'carlos.eduardo@email.com',
    city: 'São Paulo/SP',
    roomNumber: '101',
    checkIn: '2026-09-02',
    checkOut: '2026-09-06',
    numGuests: 2,
    dailyRate: 220,
    discount: 0,
    totalAmount: 880,
    paymentMethod: 'PIX (50% adiantado)',
    status: 'Hospedado',
    notes: 'Solicitou travesseiros antialérgicos adicionais.',
    createdAt: '2026-08-25',
  },
  {
    id: 'g-02',
    name: 'Mariana Azevedo Costa',
    document: '142.890.321-44',
    phone: '(21) 99342-8877',
    email: 'mariana.costa@email.com',
    city: 'Rio de Janeiro/RJ',
    roomNumber: '201',
    checkIn: '2026-09-03',
    checkOut: '2026-09-07',
    numGuests: 2,
    dailyRate: 340,
    discount: 0,
    totalAmount: 1360,
    paymentMethod: 'Cartão de Crédito 2x',
    status: 'Hospedado',
    notes: 'Aniversário de casamento. Deixar cartão boas-vindas.',
    createdAt: '2026-08-28',
  },
  {
    id: 'g-03',
    name: 'Roberto Albuquerque',
    document: '085.341.678-90',
    phone: '(31) 98455-1100',
    email: 'albuquerque.eng@email.com',
    city: 'Belo Horizonte/MG',
    roomNumber: '203',
    checkIn: '2026-09-01',
    checkOut: '2026-09-05',
    numGuests: 1,
    dailyRate: 340,
    discount: 40,
    totalAmount: 1320,
    paymentMethod: 'Transferência Bancária',
    status: 'Hospedado',
    notes: 'Check-out antecipado previsto às 09:00.',
    createdAt: '2026-08-20',
  },
  {
    id: 'g-04',
    name: 'Beatriz Vasconcelos',
    document: '331.782.905-22',
    phone: '(41) 99123-4567',
    email: 'beatriz.vasc@email.com',
    city: 'Curitiba/PR',
    roomNumber: '301',
    checkIn: '2026-09-04',
    checkOut: '2026-09-09',
    numGuests: 2,
    dailyRate: 520,
    discount: 0,
    totalAmount: 2600,
    paymentMethod: 'Cartão de Crédito à vista',
    status: 'Hospedado',
    notes: 'Chegada tardia confirmada após as 20h.',
    createdAt: '2026-09-01',
  },
  {
    id: 'g-05',
    name: 'Felipe & Camila Brandão',
    document: '419.602.118-73',
    phone: '(19) 98833-2211',
    email: 'felipe.brandao@email.com',
    city: 'Campinas/SP',
    roomNumber: 'CH-02',
    checkIn: '2026-09-03',
    checkOut: '2026-09-08',
    numGuests: 3,
    dailyRate: 460,
    discount: 0,
    totalAmount: 2300,
    paymentMethod: 'PIX Integral',
    status: 'Hospedado',
    notes: 'Cama extra para criança de 6 anos.',
    createdAt: '2026-08-15',
  },
  {
    id: 'g-06',
    name: 'Família Mendonça',
    document: '512.904.771-08',
    phone: '(11) 97722-9900',
    email: 'mendonca.adv@email.com',
    city: 'Santos/SP',
    roomNumber: 'VILA-01',
    checkIn: '2026-09-02',
    checkOut: '2026-09-10',
    numGuests: 5,
    dailyRate: 980,
    discount: 240,
    totalAmount: 7600,
    paymentMethod: 'Cartão Corporativo',
    status: 'Hospedado',
    notes: 'Vila com churrasqueira e piscina aquecida reservada.',
    createdAt: '2026-08-10',
  },
  {
    id: 'g-07',
    name: 'Luciana Martins Pereira',
    document: '189.234.901-55',
    phone: '(61) 99876-5432',
    email: 'luciana.mp@email.com',
    city: 'Brasília/DF',
    roomNumber: '102',
    checkIn: '2026-09-08',
    checkOut: '2026-09-12',
    numGuests: 2,
    dailyRate: 220,
    discount: 0,
    totalAmount: 880,
    paymentMethod: 'Aguardando check-in',
    status: 'Confirmada',
    notes: 'Reserva pelo portal direto. Sinal pago 30%.',
    createdAt: '2026-09-02',
  },
  {
    id: 'g-08',
    name: 'Danilo Ramos Siqueira',
    document: '274.551.982-12',
    phone: '(85) 98111-4477',
    email: 'danilo.ramos@email.com',
    city: 'Fortaleza/CE',
    roomNumber: 'CH-01',
    checkIn: '2026-09-11',
    checkOut: '2026-09-15',
    numGuests: 2,
    dailyRate: 460,
    discount: 50,
    totalAmount: 1790,
    paymentMethod: 'PIX',
    status: 'Confirmada',
    notes: 'Lua de mel. Preparar espumante cortesia na chegada.',
    createdAt: '2026-09-03',
  }
];

export const INITIAL_RATE_PLANS: RatePlan[] = [
  {
    id: 'rate-1',
    roomType: 'Standard',
    lowSeasonRate: 190,
    midSeasonRate: 240,
    highSeasonRate: 310,
    holidayRate: 420,
    extraPersonRate: 70,
    minNights: 1,
  },
  {
    id: 'rate-2',
    roomType: 'Luxo',
    lowSeasonRate: 290,
    midSeasonRate: 360,
    highSeasonRate: 450,
    holidayRate: 600,
    extraPersonRate: 90,
    minNights: 2,
  },
  {
    id: 'rate-3',
    roomType: 'Suíte Master',
    lowSeasonRate: 450,
    midSeasonRate: 550,
    highSeasonRate: 690,
    holidayRate: 890,
    extraPersonRate: 120,
    minNights: 2,
  },
  {
    id: 'rate-4',
    roomType: 'Chalé Vista',
    lowSeasonRate: 390,
    midSeasonRate: 480,
    highSeasonRate: 620,
    holidayRate: 780,
    extraPersonRate: 100,
    minNights: 2,
  },
  {
    id: 'rate-5',
    roomType: 'Vila Privativa',
    lowSeasonRate: 850,
    midSeasonRate: 1050,
    highSeasonRate: 1350,
    holidayRate: 1800,
    extraPersonRate: 150,
    minNights: 3,
  },
];

export const INITIAL_WORKPLACES: string[] = [
  'Cozinha',
  'Recepção',
  'Governança / Camareiras',
  'Manutenção',
  'Restaurante / Bar',
  'Administração & Gerência',
  'Portaria & Segurança',
  'Jardinagem & Lazer',
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-01',
    name: 'Maria Aparecida Silva',
    role: 'Cozinheira Chefe',
    workplace: 'Cozinha',
    phone: '(11) 98765-1122',
    email: 'maria.cozinha@hotelrecanto.com.br',
    salary: 2850,
    hireDate: '2024-03-15',
    document: '234.567.890-12',
    status: 'ativo',
    notes: 'Responsável pelo café da manhã colonial e cardápio de almoço.',
  },
  {
    id: 'emp-02',
    name: 'Lucas Mendonça',
    role: 'Recepcionista Noturno',
    workplace: 'Recepção',
    phone: '(11) 97654-3344',
    email: 'lucas.recepcao@hotelrecanto.com.br',
    salary: 2450,
    hireDate: '2024-08-01',
    document: '345.678.901-23',
    status: 'ativo',
    notes: 'Turno das 22h às 06h. Fluente em inglês e espanhol.',
  },
  {
    id: 'emp-03',
    name: 'Joana Prado Lima',
    role: 'Camareira Líder',
    workplace: 'Governança / Camareiras',
    phone: '(11) 96543-5566',
    email: 'joana.governanca@hotelrecanto.com.br',
    salary: 2200,
    hireDate: '2023-11-10',
    document: '456.789.012-34',
    status: 'ativo',
    notes: 'Coordenação de higienização de quartos e controle do enxoval.',
  },
  {
    id: 'emp-04',
    name: 'José Carlos Nogueira',
    role: 'Técnico de Manutenção Predial',
    workplace: 'Manutenção',
    phone: '(11) 95432-7788',
    email: 'manutencao@hotelrecanto.com.br',
    salary: 2650,
    hireDate: '2024-01-20',
    document: '567.890.123-45',
    status: 'ativo',
    notes: 'Instalações elétricas, hidráulica e reparos gerais nas acomodações.',
  },
];

// Starter rooms for a brand new hotel/pousada registration (all available, zero guests)
export const STARTER_CLEAN_ROOMS: Room[] = [
  {
    id: 'r-101',
    number: '101',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-102',
    number: '102',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-103',
    number: '103',
    type: 'Standard',
    area: 'Bloco Principal - Térreo',
    status: 'livre',
    dailyRate: 220,
    capacity: 2,
  },
  {
    id: 'r-201',
    number: '201',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'livre',
    dailyRate: 340,
    capacity: 3,
  },
  {
    id: 'r-202',
    number: '202',
    type: 'Luxo',
    area: 'Bloco Superior - Varanda',
    status: 'livre',
    dailyRate: 340,
    capacity: 3,
  },
  {
    id: 'r-301',
    number: '301',
    type: 'Suíte Master',
    area: 'Cobertura',
    status: 'livre',
    dailyRate: 520,
    capacity: 4,
  },
];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-001',
    code: 'BEB-01',
    product: 'Água Mineral 500ml Sem Gás',
    brandModel: 'Crystal - Garrafa Pet 500ml',
    quantity: 12,
    targetQuantity: 100,
    lastPurchasePrice: 1.85,
    alertThresholdPercent: 20, // 12% is below 20% -> ALERT RED on top
    unit: 'un',
    category: 'Frigobar & Bebidas',
    lastPurchaseDate: '2026-09-01',
    notes: 'Para reposição nos frigobares e restaurante.',
  },
  {
    id: 'inv-002',
    code: 'AMN-02',
    product: 'Sabonete em Barra 20g Miniatura',
    brandModel: 'Natura - Linha Hotelaria Erva Doce',
    quantity: 15,
    targetQuantity: 150,
    lastPurchasePrice: 0.95,
    alertThresholdPercent: 15, // 10% is below 15% -> ALERT RED on top
    unit: 'un',
    category: 'Higiene & Amenities',
    lastPurchaseDate: '2026-08-28',
    notes: 'Kit boas-vindas dos banheiros.',
  },
  {
    id: 'inv-003',
    code: 'LIM-01',
    product: 'Desinfetante Concentrado Floral 5L',
    brandModel: 'Veja - Galão Institucional 5L',
    quantity: 2,
    targetQuantity: 10,
    lastPurchasePrice: 32.90,
    alertThresholdPercent: 30, // 20% is below 30% -> ALERT RED on top
    unit: 'gl',
    category: 'Limpeza & Lavanderia',
    lastPurchaseDate: '2026-08-15',
    notes: 'Uso exclusivo da equipe de governança.',
  },
  {
    id: 'inv-004',
    code: 'ROU-01',
    product: 'Toalha de Banho Branca 500g',
    brandModel: 'Teka - Hotel Line 70x140cm 100% Algodão',
    quantity: 48,
    targetQuantity: 60,
    lastPurchasePrice: 38.50,
    alertThresholdPercent: 20, // 80% is normal
    unit: 'un',
    category: 'Rouparia & Enxoval',
    lastPurchaseDate: '2026-08-20',
    notes: 'Estoque reserva do roupeiro central.',
  },
  {
    id: 'inv-005',
    code: 'ROU-02',
    product: 'Lençol Casal com Elástico 200 Fios',
    brandModel: 'Santista - Hotelaria Percal Branco',
    quantity: 32,
    targetQuantity: 40,
    lastPurchasePrice: 54.00,
    alertThresholdPercent: 25, // 80% is normal
    unit: 'un',
    category: 'Rouparia & Enxoval',
    lastPurchaseDate: '2026-08-10',
    notes: 'Enxoval padrão das camas de casal.',
  },
  {
    id: 'inv-006',
    code: 'AMN-01',
    product: 'Shampoo & Condicionador 2 em 1 30ml',
    brandModel: 'Real Amenities - Frasco 30ml',
    quantity: 85,
    targetQuantity: 200,
    lastPurchasePrice: 1.25,
    alertThresholdPercent: 20, // 42.5% is normal
    unit: 'un',
    category: 'Higiene & Amenities',
    lastPurchaseDate: '2026-09-02',
    notes: 'Frascos biodegradáveis para hóspedes.',
  },
  {
    id: 'inv-007',
    code: 'BEB-02',
    product: 'Refrigerante Coca-Cola Lata 350ml',
    brandModel: 'Coca-Cola - Original Sabor',
    quantity: 36,
    targetQuantity: 48,
    lastPurchasePrice: 3.40,
    alertThresholdPercent: 25, // 75% is normal
    unit: 'lata',
    category: 'Frigobar & Bebidas',
    lastPurchaseDate: '2026-09-04',
    notes: 'Frigobar quartos e quiosque.',
  },
  {
    id: 'inv-008',
    code: 'LIM-02',
    product: 'Papel Higiênico Folha Dupla Fardo c/ 64',
    brandModel: 'Neve Institucional - Rolos 30m',
    quantity: 14,
    targetQuantity: 20,
    lastPurchasePrice: 79.90,
    alertThresholdPercent: 20, // 70% is normal
    unit: 'fardo',
    category: 'Limpeza & Lavanderia',
    lastPurchaseDate: '2026-08-25',
    notes: 'Depósito do Bloco Principal.',
  },
  {
    id: 'inv-009',
    code: 'ALM-01',
    product: 'Café Especial em Grãos 1kg',
    brandModel: 'Pilão - Espresso Gourmet Torra Média',
    quantity: 9,
    targetQuantity: 15,
    lastPurchasePrice: 44.00,
    alertThresholdPercent: 25, // 60% is normal
    unit: 'pct',
    category: 'Alimentos & Café da Manhã',
    lastPurchaseDate: '2026-09-05',
    notes: 'Máquina automática de café da manhã.',
  },
];

export const INITIAL_STOCK_EXITS: StockExitRecord[] = [
  {
    id: 'exit-001',
    itemId: 'inv-001',
    itemCode: 'BEB-01',
    productName: 'Água Mineral 500ml Sem Gás',
    brandModel: 'Crystal - Garrafa Pet 500ml',
    quantity: 6,
    destination: 'Frigobar - Quarto 101',
    responsibleName: 'Ana Paula (Camareira)',
    date: '2026-09-10',
    time: '10:15',
    notes: 'Reposição diária de frigobar para novo hóspede.',
    createdAt: '2026-09-10T10:15:00',
  },
  {
    id: 'exit-002',
    itemId: 'inv-004',
    itemCode: 'ROU-01',
    productName: 'Toalha de Banho Branca 500g',
    brandModel: 'Teka - Hotel Line 70x140cm 100% Algodão',
    quantity: 4,
    destination: 'Quarto 201 (Suíte Luxo)',
    responsibleName: 'Maria Santos (Governanta)',
    date: '2026-09-10',
    time: '11:40',
    notes: 'Troca de enxoval solicitada na recepção.',
    createdAt: '2026-09-10T11:40:00',
  },
  {
    id: 'exit-003',
    itemId: 'inv-003',
    itemCode: 'LIM-01',
    productName: 'Desinfetante Concentrado Floral 5L',
    brandModel: 'Veja - Galão Institucional 5L',
    quantity: 1,
    destination: 'Limpeza Geral - Bloco Térreo',
    responsibleName: 'Marcos Silva (Manutenção)',
    date: '2026-09-11',
    time: '08:30',
    notes: 'Higienização de pisos e áreas comuns.',
    createdAt: '2026-09-11T08:30:00',
  },
];

